### PR TITLE
 CLI by click: added --timezone, --days and --print-timezones 

### LINKED ISSUE #22: Command line options for default local timezone and for windows size
The script (as currently in master) expects user to edit some configuration in the code:
- window length (in days)
- default time zone.

I would ignore the default timezone as it is very likely user will succeed installing proper package for this (if there is real chance, it would be a problem, we shall add that switch).

In PR #21 is modified version of the code, which internally already expects parameter for windows length. The only thing missing is to add some command line argument parsing for it (either using argparse, or another package, I personally enjoy using click).

### PR DESCRIPTION
**Pull request by vlcinsky**
Usage changed a bit:
```
$ ical2orgpy
Usage: ical2orgpy [OPTIONS] ICS_FILE ORG_FILE

Error: Missing argument "ics_file".
$ ical2orgpy --help
Usage: ical2orgpy [OPTIONS] ICS_FILE ORG_FILE

  Convert ICAL format into org-mode.

  Files can be set as explicit file name, or `-` for stdin or stdout::

      $ ical2orgpy in.ical out.org
      $ ical2orgpy in.ical - > out.org  
      $ cat in.ical | ical2orgpy - out.org
      $ cat in.ical | ical2orgpy - - > out.org

Options:
  -p, --print-timezones     Print acceptable timezone names and exit.
  -d, --days INTEGER RANGE  Window length in days (left & right from current
                            time). Has to be positive.
  -t, --timezone TEXT       Timezone to use. (local timezone by default)
  -h, --help                Show this message and exit.
```

fix #22

### CODE REVIEW

**Comment by asoroa** [comment]
Hi,
sorry for the delay, but I'm having quite a bit time trying to understand what you are doing, which falls well outside my area of expertise.
One thing I'm worried with is how to call the ical2orgpy.py. I usually do it via a cron job, which regularly calls a script that grabs from my google calendar and creates a new org document using ical2org.py (as explained [here](http://orgmode.org/worg/org-tutorials/org-google-sync.html#org1630cfe) ). The way to call ical2org.py is straightforward:
`~/bin/ical2org.py $ICSFILE > $ORGTMPFILE`
How should I do this now with the new package?

**Comment by vlcinsky** [comment]
## Installing into user profile
This is quick and a bit dirty way. Assuming, you have pip (or pip3) installed:
```
$ pip install --user ical2orgpy
$ ~/.local/bin/ical2orgpy
```

You may use that path in your cron job.

If you want to test it from current project:
```
$ cd <to project folder>
$ pip install --user .
```

and you are done.

## Using virtualenv
If you do not want to spoil your global or user python installation, you have to use virtualenv. There are many ways, I prefer `tox`, others `$ python -m venv`, other `virtualenvwrapper`. This I can describe later. One example with tox is part of issue #20. I can elaborate on other installation techniques later on.

## What makes the difference with python package
- easy to install into user profile or virtualenv
- all dependencies are installed with it (so there is no question, if some system-wide package is available or not)

**Comment by vlcinsky** [comment]
@asoroa I have updated my previous instructions as the very first instruction expected the package being available on pypi, what is currently not true. Sorry for confusion.

Feel free to ask for any further assistance.

**Comment by vlcinsky** [comment]
@asoroa the simplest procedure can be:
```
$ curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
$ cd {ical2orgpy-project-directory}
$ pipsi install .
```

More details in issue #20.

**Comment by asoroa** [comment]
OK, thanks. I've installed locally according with your instructions it works, but when trying my script, ical2orgpy fails:
```
/home/asoroa/.local/lib/python3.5/site-packages/ical2orgpy.py:291: UserWarning: Warning: an exception occured: 'range' object does not support item deletion
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/asoroa/.local/bin/ical2orgpy", line 10, in <module>
    sys.exit(main())
  File "/home/asoroa/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/asoroa/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/asoroa/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/asoroa/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/asoroa/.local/lib/python3.5/site-packages/ical2orgpy.py", line 351, in main
    convertor(ics_file, org_file)
  File "/home/asoroa/.local/lib/python3.5/site-packages/ical2orgpy.py", line 262, in __call__
    event_iter = generate_event_iterator(comp, start, end, self.tz)
  File "/home/asoroa/.local/lib/python3.5/site-packages/ical2orgpy.py", line 72, in generate_event_iterator
    EventRecurYearlyIter(comp, timeframe_start, timeframe_end, tz)
  File "/home/asoroa/.local/lib/python3.5/site-packages/ical2orgpy.py", line 212, in __init__
    del self.years[comp['RRULE']['COUNT'][0]:]
TypeError: 'range' object does not support item deletion
```
I need some time to dig into this.

**Comment by vlcinsky** [comment]
Great.

This sounds like python3 related problem. I guess, it will work well under python 2.

On lines 206 and 211 I see, you assing result of `range` into `self.years`:

```python
        self.years = range(self.start.year, self.end.year + 1)
        if 'COUNT' in comp['RRULE']:
            if self.is_until:
                msg = "UNTIL and COUNT MUST NOT occur in the same 'recur'"
                raise ValueError(msg)
            self.years = range(self.ev_start.year, self.end.year + 1)
            del self.years[comp['RRULE']['COUNT'][0]:]
```
As `range` is new type of object in python3, you can probably fix that by:

```python
        self.years = list(range(self.start.year, self.end.year + 1))
        if 'COUNT' in comp['RRULE']:
            if self.is_until:
                msg = "UNTIL and COUNT MUST NOT occur in the same 'recur'"
                raise ValueError(msg)
            self.years = list(range(self.ev_start.year, self.end.year + 1))
            del self.years[comp['RRULE']['COUNT'][0]:]
```

**Comment by vlcinsky** [comment]
Added proposed modification to my pull request, you may try it.

**Comment by asoroa** [comment]
Ok, now it works, thanks! The strange thing is that the previous script didn't complain with neither python2 or python3, but whatever ...
Anyway, I'm going to merge your PR into master. I've pushed a new commit (7ccaa3) adding the GPL v3 license. If you agree, I will rebase your py2py3 branch into the new master and push the result into the main repo (I prefer to maintain a linear history if possible).
A million thanks for putting so much effort into ical2org.py (hereafter called ical2orgpy). The script is in much better shape now! I suppose that the next step would be to upload the package to pypi?

**Comment by vlcinsky** [comment]
@asoroa (put my comment to wrong place)

Sure, feel free to rebase and pull into master.

I will come with more details soon.

**Comment by vlcinsky** [comment]
# "You shall not pass" aka "the script didn't complain"

https://github.com/asoroa/ical2org.py/blob/master/ical2org.py#L252 there was

```python
try:
	some_code_here
except:
	pass
```

The last two lines is antipattern as it effectively hides many errors. It is possible, this hid the issue. My modification is raising.

# Assigning package version by adding version tag

Package shall be versioned and my favourite `pbr` allows not only clean `setup.py` and `setup.cfg`, but also setting up version by means of git tag:

```bash
$ git tag -a 0.1
```
Once you do that, you will notice, that `tox` as well as `$ python setup.py sdist` are building the package with new version assinged. Even better, during development, it will increment the version suffixing it with `dev12`.

*WARNING* tags must be pushed and pulled separately so one has to use ```$ git push --tags``` and ```$ git pull --tags```.

# python packages with `pbr` (discussion)
The `pbr` package is used by OpenStack for all the tools they have and I really enjoy it (all my packages updated within last two years use it). What I like on using `pbr` is:

- trivial `setup.py` file
- easy to read `setup.cfg` with all the metadata put into it
- all dependencies put into `requirements.txt`
- reuse of `README.rst` for the package
- versions are assigned simply by setting git tag

There are other advantages:
- file `ChangeLog` generated from commit messages
- file `AUTHORS` generated from authors mentioned in commits.

Anyway, I do not keep the last two files directly in my repo, I only use them as great source for updating NEWS.rst and AUTHORS.rst manually. You may add the `ChangeLog` and `AUTHORS` into `.gitignore`.

There are some drawbacks and minor problems:
- git tags must be explicitly pushed/pulled across different repositories. This is extra step to keep in mind.
- it sometime surprises by omiting a file - so if you wonder, why the final package miss some of the files, make sure the missing file is commited to git repository.
- it works best for developers using git.

I feel, all the drawbacks are worth to overcome as the benefits are much bigger.

Anyway, if you prefer not to use `pbr`, I have no objections if you or anyone else rewrites the `setup.py` to be `pbr` independent.

# Pushing the package into pypi
You shall find some instructions how to do that. If you get into problems, I might try helping you. As I have only few packages on pypi, I do not have simpler instructions to follow. I use `devpi` private pypi server, allowing to push even to pypi server, but I guess it is not worth unless you already use devpi for your own development.

Anyway, before pushing to pypi.python.org, take care of:
- the package works. If you push it and find a problem, you shall push higher version (no way to override existing one, it would be insane anyway).
- fixed package versions in `requirements.txt`. It is advised to define dependency on fixed package versions. Many developers (incl. me) ignore it, but there are tools, which may help it and it is recommended for good reasons.
- *update metadata in `setup.cfg` pointing to GPL version*. It will make the information more visible.

# Thanks for your script
Regardless of all the "cleaning" work I did, the core comes from you (and other contributors). I did not dive into it deeper than necessary as it was rather easy to reorganize and things seemed working to me. Before I started modifications, I converted my large ics file into org one and used that to make sure, I did not break things. More tests can be added in future, if needed (I skipped detailed tests for recurring events).

**Pull request closed without merging**
